# -*- coding: utf-8 -*-
"""Logistic regression model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0elaq0rmyleoA635A3JbQp9yJU1lhcG

#A model using logistic Regression to classigy a bank transition to eithe deposit or non deposit

##Importing Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""##Loading the data set

"""

data = pd.read_csv("bank-full.csv", sep=";")

print(data.head())

"""## Encode categorical data

"""

le = LabelEncoder()
for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = le.fit_transform(data[column])

"""## Feature Selection and Target Variable

"""

X = data.drop("y", axis=1)
y = data["y"]

"""## Splitting the Dataset into Training and Testing Sets"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## Model Selection


"""

model = LogisticRegression(max_iter=1000)

"""## Training the Model

"""

model.fit(X_train, y_train)

"""## Making Predictions


"""

y_pred = model.predict(X_test)

"""## Model Evaluation (Accuracy)


"""

print("Accuracy:", accuracy_score(y_test, y_pred))